### ISSUE TITLE
Lesss flexible code 

### ISSUE THREAD

**Issue by Deepanshu-Rohilla** [just-kidding-yadav/Matrix-Calculator#1]
I think one can use `numpy` for most of these calculations and even much more than this.
These code might only give you basic practice but you can do competitive programming for that.
Basically, this repository is useless and I don't find any learning in this "project".

**Comment by just-kidding-yadav** [comment]
You are right. There is no use in learning any implementation because there are pre defined functions for most of them. So as per you everything is useless. Dear, you need to understand that this is a practice project. It's not useless, just is basic. If everyone keeps on thinking like that, there would be no learning, just criticism. So, please give some positive feedback only. It's my humble request to you that spread love and positivity and not hatred.

**Comment by Deepanshu-Rohilla** [comment]
My point was that it makes no sense in hosting this on GitHub. If things work like that, I would have hundreds and thousands of  repository on my account. 
If you want to keep it in an organised way, maybe you can one repo as "basic-practice" or something and log all your "practice" there.
I did not say that this is useless. Just that don't make another repository for every other problem you do.
Peace
